version: '3.9'

services:
  backend:
    build: .
    container_name: coordinadora-backend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    command: npm run dev
